export interface UserData {
  created_at: string; // Fecha de creación en formato ISO (YYYY-MM-DDTHH:MM:SS) [web:1]
  password_hash: string; // Hash de la contraseña [web:1]
  updated_at: string; // Fecha de actualización en formato ISO (YYYY-MM-DDTHH:MM:SS) [web:1]
  user_address1: string; // Dirección principal [web:1]
  user_address2: string; // Dirección adicional [web:1]
  user_birthdate: string; // Fecha de nacimiento (YYYY-MM-DD) [web:1]
  user_city: string; // Ciudad [web:1]
  user_company: string; // Empresa [web:1]
  user_device_id: string; // Identificador único del dispositivo [web:1]
  user_email: string; // Correo electrónico [web:1]
  user_first_name: string; // Nombre [web:1]
  user_id: number; // ID único del usuario [web:1]
  user_last_name: string; // Apellido [web:1]
  user_license: string; // Licencia [web:1]
  user_phone1: string; // Teléfono principal [web:1]
  user_phone2: string; // Teléfono secundario [web:1]
  user_postal_code: string; // Código postal [web:1]
  user_role: string; // Rol del usuario [web:1]
  user_state: string; // Estado o provincia [web:1]
  username: string; // Nombre de usuario [web:1]
  user_confirmed: string | null;
}
