import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import ClientProvider from "@/components/providers/ClientProvider";

const font_family = Fira_Sans({
  variable: "--font-family",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Escrow",
  description: "Generated by Quatrobus",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="apple-touch-icon" href="/icons/icon-192.png" />
      </head>
      <body className={`${font_family.variable} antialiased overflow-x-hidden`}>
        <ClientProvider />
        <Toaster richColors visibleToasts={3} />
        {children}
      </body>
    </html>
  );
}
